name: Build and Commit PDF to docs/

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Copy to docs folder
        run: |
          mkdir -p docs
          cp main.pdf docs/pregdose_protocol.pdf
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>PregDose PDF</title></head><body><h1>PregDose Protocol</h1><p><a href="pregdose_protocol.pdf">📄 Download PDF</a></p></body></html>' > docs/index.html

      - name: Commit and push PDF and index.html
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Update compiled PDF and index.html"
          git push
