name: Build and Upload LaTeX PDF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: pregdose-pdf
          path: main.pdf
